[build]
  command = "npm run build"
  publish = "dist"

[[headers]]
  for = "/*"
  [headers.values]
    X-Debug-Message = "Hatomaran Project"
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "*.svg"
  [headers.values]
    Content-Type = "image/svg+xml"
