backend:
  name: git-gateway
  branch: master

media_folder: "public/images/projects"
public_folder: "/images/projects"

collections:
  - name: "projects"
    label: "Projects"
    folder: "content/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Название", name: "title", widget: "string", required: true }
      - { label: "Описание", name: "description", widget: "text", required: false }
      - { label: "Нужна ли отдельная страница?", name: "isOpen", widget: "boolean", default: false, required: false }
      - { label: "Тэг", name: "tag", widget: "select",
          options: [ "animation", "project" ],
          required: true }
      - label: "Изображение"
        name: "images"
        widget: "list"
        fields:
          - {
            label: "Изображение",
            name: "url",
            widget: "image",
            required: true
          }
          - {
            label: "Название",
            name: "title",
            widget: "string",
            required: false
          }
